import * as faker from 'faker';
import { Facility } from './useFacilitiesState';

export const facilitiesList: Facility[] = [
  {
    id: faker.datatype.uuid(),
    facilityName: 'Ares Training Facility',
    address: '35615 North Treasure Island Avenue',
    city: 'Leesburg',
    state: 'FL',
    zip: '34788',
    country: 'US',
    primaryPhoneNumber: '(352) 321-8102',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'www.AresTrainingFacility.com',
    facilityType: 'Outdoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'instagram',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Calvin.Roosevelt',
    facilityAdministratorPhone: '523446',
    facilityAdministratorEmail: 'Calvin.Roosevelt@xyz.com',
    hoursOfOperation: '[9:00 a.m. - 10:00 p.m.]',
    paymentInformation: '[Credit Card,Bank Account, Check]',
    nssfMember: false,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 1,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'Sheridan Arms',
    address: '8259 Tittabawassee Road',
    city: 'Saginaw',
    state: 'MI',
    zip: '48603',
    country: 'US',
    primaryPhoneNumber: '(989) 607-0130',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'www.sheridanarms.com',
    facilityType: 'Indoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'pinterest',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Martin.Tyler',
    facilityAdministratorPhone: '17606',
    facilityAdministratorEmail: 'Martin.Tyler@xyz.com',
    hoursOfOperation: '8:00 a.m. - 9:00 p.m.',
    paymentInformation: '[Credit Card,Paypal, Check]',
    nssfMember: true,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 2,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'SAFESHOOT',
    address: '10 Kieffer Lane',
    city: 'Kingston',
    state: 'NY',
    zip: '12401',
    country: 'US',
    primaryPhoneNumber: '845-443-7727',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'www.safeshootny.com',
    facilityType: 'Indoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'instagram',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Warren.Nixon',
    facilityAdministratorPhone: '67915',
    facilityAdministratorEmail: 'Warren.Nixon@xyz.com',
    hoursOfOperation: '[9:00 a.m. - 10:00 p.m.]',
    paymentInformation: '[Credit Card,Bank Account, Paypal, Check]',
    nssfMember: true,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 3,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'Gun Runner Shooting Sports',
    address: '2763 FM 1125',
    city: 'Bowie',
    state: 'TX',
    zip: '76230',
    country: 'US',
    primaryPhoneNumber: '940-343-7603',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'gr-ss.com',
    facilityType: 'Outdoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'facebook',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Gerald.Tyler',
    facilityAdministratorPhone: '645226',
    facilityAdministratorEmail: 'Gerald.Tyler@xyz.com',
    hoursOfOperation: '[9:00 a.m. - 10:00 p.m.]',
    paymentInformation: '[Credit Card,Bank Account, Paypal, Check]',
    nssfMember: false,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 4,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'Bayshore Sportsmans Club',
    address: '315 Arizona Ave',
    city: 'Villas',
    state: 'NJ',
    zip: '08251',
    country: 'US',
    primaryPhoneNumber: '(609) 889-8716',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'bayshoresportsmansclub.com',
    facilityType: 'Indoor/Outdoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'instagram',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'James.Harrison',
    facilityAdministratorPhone: '202262',
    facilityAdministratorEmail: 'James.Harrison@xyz.com',
    hoursOfOperation: '8:00 a.m. - 10:00 p.m.',
    paymentInformation: '[Credit Card,Bank Account, Check]',
    nssfMember: false,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 5,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'RTSP Union, LLC',
    address: '2438 US Highway 22',
    city: 'Union',
    state: 'NJ',
    zip: '07083',
    country: 'US',
    primaryPhoneNumber: '973-434-7600',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'www.rtsponline.com',
    facilityType: 'Indoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'instagram',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Ronald.Taft',
    facilityAdministratorPhone: '96732',
    facilityAdministratorEmail: 'Ronald.Taft@xyz.com',
    hoursOfOperation: '[9:00 a.m. - 10:00 p.m.]',
    paymentInformation: '[Credit Card,Bank Account, Check]',
    nssfMember: false,
    nssfRating: 5,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 6,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'Hyatt Farms Sporting Clays',
    address: '990 Burnsville Church Road',
    city: 'Polkton',
    state: 'NC',
    zip: '28135',
    country: 'US',
    primaryPhoneNumber: '704-826-6014',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'www.ncsportingclays.com',
    facilityType: 'Outdoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'instagram',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Gerald.Polk',
    facilityAdministratorPhone: '823545',
    facilityAdministratorEmail: 'Gerald.Polk@xyz.com',
    hoursOfOperation: '[9:00 a.m. - 10:00 p.m.]',
    paymentInformation: '[Credit Card,Paypal, Check]',
    nssfMember: true,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 7,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'Shawnee Skies Training Center and Shooting Center',
    address: '11245 S.705 Road',
    city: 'Wyandotte',
    state: 'OK',
    zip: '743780',
    country: 'US',
    primaryPhoneNumber: '918-238-2529',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'shawneeskies.com',
    facilityType: 'Outdoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'pinterest',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Ronald.Hayes',
    facilityAdministratorPhone: '142037',
    facilityAdministratorEmail: 'Ronald.Hayes@xyz.com',
    hoursOfOperation: '[9:00 a.m. - 10:00 p.m.]',
    paymentInformation: '[Credit Card,Bank Account, Check]',
    nssfMember: true,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 8,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'The Training Range',
    address: '4445 Mahoning Ave',
    city: 'Youngstown',
    state: 'OH',
    zip: '44515',
    country: 'US',
    primaryPhoneNumber: '(330) 953-2030',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'www.thetrainingrange.com',
    facilityType: 'Indoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'instagram',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Benjamin.Wilson',
    facilityAdministratorPhone: '558295',
    facilityAdministratorEmail: 'Benjamin.Wilson@xyz.com',
    hoursOfOperation: '[9:00 a.m. - 10:00 p.m.]',
    paymentInformation: '[Credit Card,Paypal, Check]',
    nssfMember: true,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 9,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'On Guard Defense Training Center',
    address: '66211 Bethel Road',
    city: 'New Plymouth',
    state: 'OH',
    zip: '45654',
    country: 'US',
    primaryPhoneNumber: '(740) 596-1984',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'onguarddefense.com',
    facilityType: 'Outdoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'twitter',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'William.Carter',
    facilityAdministratorPhone: '408976',
    facilityAdministratorEmail: 'William.Carter@xyz.com',
    hoursOfOperation: '8:00 a.m. - 9:00 p.m.',
    paymentInformation: '[Credit Card,Bank Account, Check]',
    nssfMember: true,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 10,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: '5H Shooting Sports',
    address: '19105 Country Road 4235',
    city: 'Frankston',
    state: 'TX',
    zip: '75763',
    country: 'US',
    primaryPhoneNumber: '903-876-2772',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'www.5houtdoors.com',
    facilityType: 'Outdoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'facebook',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Woodrow.Fillmore',
    facilityAdministratorPhone: '685140',
    facilityAdministratorEmail: 'Woodrow.Fillmore@xyz.com',
    hoursOfOperation: '8:00 a.m. - 10:00 p.m.',
    paymentInformation: '[Credit Card,Bank Account, Check]',
    nssfMember: true,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 11,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'Chief Wa Ke De',
    address: '16067 IN-120',
    city: 'Bristol',
    state: 'IN',
    zip: '46507',
    country: 'US',
    primaryPhoneNumber: '(574) 358-2436',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'www.sjvrp.com',
    facilityType: 'Outdoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'instagram',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Martin.McKinley',
    facilityAdministratorPhone: '333660',
    facilityAdministratorEmail: 'Martin.McKinley@xyz.com',
    hoursOfOperation: '8:00 a.m. - 9:00 p.m.',
    paymentInformation: '[Credit Card,Bank Account, Paypal, Check]',
    nssfMember: false,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 12,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: "Buck & Doe's Mercantile",
    address: '24250 US 281',
    city: 'San Antonio',
    state: 'TX',
    zip: '78258',
    country: 'US',
    primaryPhoneNumber: '830-980-3637',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'www.buckdoes.com',
    facilityType: 'Indoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'facebook',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Bill.Jackson',
    facilityAdministratorPhone: '152678',
    facilityAdministratorEmail: 'Bill.Jackson@xyz.com',
    hoursOfOperation: '8:00 a.m. - 9:00 p.m.',
    paymentInformation: '[Credit Card,Bank Account, Check]',
    nssfMember: true,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 13,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'Survival Decision',
    address: '4450 Vance Road',
    city: 'Holly Hill',
    state: 'SC',
    zip: '29059',
    country: 'US',
    primaryPhoneNumber: '803-857-4075',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'http://www.survivaldecision.com',
    facilityType: 'Outdoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'facebook',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Franklin.Taylor',
    facilityAdministratorPhone: '572502',
    facilityAdministratorEmail: 'Franklin.Taylor@xyz.com',
    hoursOfOperation: '8:00 a.m. - 10:00 p.m.',
    paymentInformation: '[Credit Card,Bank Account, Check]',
    nssfMember: false,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 14,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'Shoot Point Blank - Mentor',
    address: '5957 Heisley Rd',
    city: 'Mentor',
    state: 'OH',
    zip: '44060',
    country: 'US',
    primaryPhoneNumber: '(440) 639-1911',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'https://shootpointblank.com/cleveland-shooting-range',
    facilityType: 'Indoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'instagram',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'George.Adams',
    facilityAdministratorPhone: '984145',
    facilityAdministratorEmail: 'George.Adams@xyz.com',
    hoursOfOperation: '8:00 a.m. - 10:00 p.m.',
    paymentInformation: '[Credit Card,Paypal, Check]',
    nssfMember: true,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 15,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  },
  {
    id: faker.datatype.uuid(),
    facilityName: 'Shoot Point Blank - Cypress',
    address: '10310 Wortham Center Drive',
    city: 'Houston',
    state: 'TX',
    zip: '77065',
    country: 'US',
    primaryPhoneNumber: '(832) 460-1585',
    secondaryPhoneNumber: '--',
    facilityWebsiteUrl: 'https://shootpointblank.com/cypress/',
    facilityType: 'Indoor',
    facilitySize: 480,
    facilityBuildingSize: 0,
    numberOfZones: 0,
    socialMedia: 'facebook',
    socialMediaUrl: 'url/path/...',
    facilityAdministratorName: 'Ulysses.Hayes',
    facilityAdministratorPhone: '462109',
    facilityAdministratorEmail: 'Ulysses.Hayes@xyz.com',
    hoursOfOperation: '[9:00 a.m. - 10:00 p.m.]',
    paymentInformation: '[Credit Card,Bank Account, Paypal, Check]',
    nssfMember: true,
    nssfRating: 0,
    rangeIoTEnabled: false,
    facilityServices: '',
    category: '',
    subcategory: '',
    secuence: 16,
    createdAt: faker.date.past().getTime(),
    updatedAt: faker.date.recent().getTime()
  }
];
